[package]
name = "hotwatch"
version = "0.2.1"
authors = ["Francesca Frangipane <francesca@comfysoft.net>"]
description = "A Rust library for conveniently watching and handling file changes."
documentation = "https://francesca64.github.io/hotwatch/docs/hotwatch"
homepage = "https://francesca64.github.io/hotwatch/"
repository = "https://github.com/francesca64/hotwatch"
readme = "README.md"
keywords = ["notify", "watch", "events", "filesystem"]
license = "MIT"

[dependencies]
notify = "4.0"
parking_lot = "0.4"
