[package]
name = "hotwatch"
version = "0.1.0"
authors = ["Francesca Frangipane <francesca@comfysoft.net>"]
keywords = ["notify", "watch", "events", "filesystem"]

[dependencies]
clippy = { git = "https://github.com/Manishearth/rust-clippy", optional = true }
notify = "2.6"
parking_lot = "0.2"

[features]
default = []
